name: Build Image on Commit and Release

on:
  push:
    tags:
      - '*'

jobs:
  bake:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -  
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Generate Distroless Docker tag
        id: docker_tag
        run: |
          DOCKER_IMAGE=${{ github.repository_owner }}/rssbridge
          DOCKER_VERSION=master
          DOCKER_VERSION=${GITHUB_REF#refs/tags/}
          TAGS="ghcr.io/${DOCKER_IMAGE}:${DOCKER_VERSION},ghcr.io/${DOCKER_IMAGE}:latest"
          echo ::set-output name=tags::${TAGS}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and Push
        uses: docker/build-push-action@v4
        with:
          tags: ${{ steps.docker_tag.outputs.tags }}
          push: true
